baseURL: 'https://immortaldevs.net/'
languageCode: 'en-us'
title: 'Immortal Devs'
theme: 'PaperMod'
enableGitInfo: true
params:
  keywords: [ immortal, devs, minecraft, mods, fabric ]
  tags: [ paradise, lost, primeval ]
  description: We are Immortal Devs. We aim to bring carefully woven experiences, built to be enjoyed now and a hundred worlds later.
  author: kalucky0
  env: production
  favicon: https://immortaldevs.net/favicon.ico
  homeInfoParams:
    Title: We are Immortal Devs ✨
    Content: A team of developers, artists, and musicians set on creating quality Minecraft mods (and perhaps even dabbling in game dev some day). You may know us for some of the finest mods fabric has to offer, such as **Paradise Lost** - _a grand dimension mod set in a pastel skyland, brooding with secrets just behind the veil_, or **Primeval** - _a complete overhaul of Minecraft's usual gameplay systems to create a rustic, "realistic" game progression_.
  mainSections: posts

  socialIcons:
    - name: "CurseForge"
      url: "https://curseforge.com/members/immortaldevs/projects"
    - name: "Modrinth"
      url: "https://modrinth.com/mod/paradise-lost"
    - name: "GitHub"
      url: "https://github.com/devs-immortal"
    - name: "Bluesky"
      url: "https://bsky.app/profile/immortaldevs.net"
    - name: "Discord"
      url: "https://discord.gg/TvuNtNYEvr"
menu:
  main:
    - identifier: primeval-wiki
      name: Primeval Wiki
      url: /wiki/primeval
      weight: 10
    # - identifier: pl-wiki
    #   name: Paradise Lost Wiki
    #   url: /wiki/paradise-lost
    #   weight: 10

minify:
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true